[package]
name = "pyre-core"
version = "0.1.0"
description = "Pyre core."

edition.workspace = true

authors = ["Orbital Drift"]
homepage = "https://odlabs.xyz"
repository = "https://github.com/orbitaldrift/pyre"
documentation = "https://docs.odlabs.xyz"

keywords = ["web", "api"]
categories = ["web-programming"]

[dependencies]
pyre-build = { workspace = true }
pyre-cli = { workspace = true }
pyre-fs = { workspace = true }
pyre-telemetry = { workspace = true }

color-eyre = { workspace = true }
thiserror = { workspace = true }

tracing = { workspace = true }

tokio = { workspace = true }
tokio-util = { workspace = true }

serde = { workspace = true }
chrono = { workspace = true }

futures = { workspace = true }
futures-util = { workspace = true }

tikv-jemallocator = { version = "0.6.0" }

uuid = { version = "1.16.0", features = ["v4"] }

bytes = "1.10.1"
once_cell = "1.21.3"
reqwest = { version = "0.12.15", default-features = false, features = [
    "http2",
    "json",
    "stream",
    "zstd",
] }

[build-dependencies]
pyre-build = { workspace = true }
color-eyre = { workspace = true }
vergen-git2 = { workspace = true }
