[server]
addr = "127.0.0.1:4433"
cert = "etc/localhost/local.cert"
key = "etc/localhost/local.key"
timeout = 10
max_conns = 512
max_body = 4096
origins = ["localhost:4433"]

[telemetry]
domain = "odrift"
mode = { Stdout = {} }
layers = ""
filter = "info"
interval = 10
temporality = { Cumulative = {} }
