[server]
addr = "127.0.0.1:4433"
cert = "etc/localhost/local.der"
key = "etc/localhost/local-key.der"
test_cert = false
secret = "etc/keys/.master.key"

[http]
timeout = 10
max_conns = 512
max_body = 1_000_000
limiter_period = 2
limiter_retain_interval = 60
origins = ["localhost:4433"]

[session]
session_days = 7

[db]
redis = "redis://localhost:6379"
pg = "postgres://postgres:postgres@localhost:5432/pyre"

[telemetry]
mode = { Stdout = {} }
layers = "metrics,traces"
level = "info"
filter = ["tower_sessions=warn", "axum_login=warn"]
interval = 10
temporality = { Cumulative = {} }

[discord]
client_id = "1363014531705471097"
client_secret = "etc/keys/.discord.key"
auth_url = "https://discord.com/api/oauth2/authorize"
token_url = "https://discord.com/api/oauth2/token"
redirect_url = "https://127.0.0.1:4433/oauth2/discord/auth"
scopes = ["identify", "email"]

[reqwest]
timeout = 5
